### ISSUE TITLE
Rotational covariance for 3D poses not being displayed properly

### ISSUE THREAD

**Issue by Ellon** [laas/rviz_plugin_covariance#13]
The current display on https://github.com/laas/rviz_plugin_covariance/commit/126ba691ba7b84973bfd9d23bf23c8deeb223d2f uses the same logic for positional and rotational covariances in 3D, which is not at all intuitive for the rotational covariance. A display like the one in the figure 2 of [this article](http://groups.csail.mit.edu/rrg/papers/icra12_aggressive_flight.pdf) would be a better option.
![rotational_covariance_example](https://cloud.githubusercontent.com/assets/2206351/13465270/29b180d8-e095-11e5-91fc-937aab94ede6.png)

**Comment by NikolausDemmel** [comment]
Just quoting myself on how the display could look for easier reference (quote from https://github.com/laas/rviz_plugin_covariance/issues/10#issuecomment-191264433)

> What I could imagine is changing the display of the orientation covariance to something that is similar to the linked-to paper above. I.e. one cone (or maybe just the 2d ellipse as in the paper) for each axis. For my 2D case that would degenerate to just two flat same-sized triangles along the x and y axes, where the length of the line that is perpenticular to the axis is 2sigma of the yaw variance ("radius" = 1 sigma). The cone along the z axis would not be visible (width 0). For me that would be nice to have, but it is not really vital currently.
