### ISSUE TITLE
Mentioned but not included: scripts/send_test_msgs.py

### ISSUE THREAD

**Issue by kisss256** [laas/rviz_plugin_covariance#18]
The file `scripts/send_test_msgs.py` is mentioned (for installing) by `CMakeLists.txt`, but does not exist in this branch. Should possibly be changed to install `send_covariance_msgs.py`, `send_covariance_msgs_2D.py`, and `send_odometry.py` instead.

**Comment by jspricke** [comment]
Should be fixed with #19.
