### ISSUE TITLE
Release into ROS

### ISSUE THREAD

**Issue by jspricke** [laas/rviz_plugin_covariance#20]
Hi,

would be great if you could release the package into the ROS distribution, so it's installable through apt-get. See: http://wiki.ros.org/bloom.

**Comment by Ellon** [comment]
Hi,

Thanks for the suggestion and the link. I think it could be a good idea. I don't have time to do it now though. I will do as soon as I have more time.

**Comment by jspricke** [comment]
Landed in rviz: https://github.com/ros-visualization/rviz/pull/1096
